### ISSUE TITLE
Parsing error with SVG <use> with xlink:href attribute

### ISSUE THREAD

**Issue by benjarwar** [vuejs/eslint-plugin-vue#52]
**Tell us about your environment**

* **ESLint Version:** 4.1.1
* **eslint-plugin-vue Version:** 3.1.3
* **Node Version:** 6.9.2

**Please show your full configuration:**

```
env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:vue/recommended
```

**What did you do? Please include the actual source code causing the issue.**

```vue
<template>
  <svg class="icon">
    <use xlink:href="#chevron"></use>
  </svg>
</template>
```

**What did you expect to happen?**
`xlink:href` attributes shouldn't cause parsing errors. We are using an SVG sprite built with [gulp-svg-sprite](https://github.com/jkphl/gulp-svg-sprite) for our iconography; this attribute refers to the icon's ID.

**What actually happened? Please include the actual, raw output from ESLint.**
Received the following `Parsing error`:

```
  0:0  error  Parsing error: Cannot read property 'startOffset' of undefined
```

The error disappears upon removal of the `xlink:href` attribute.

**Comment by benjarwar** [comment]
Also, I'm trying to silence the rule for now, but doesn't seem like I can override it. Do I need to avoid extending `plugin:vue/recommended` and add each rule manually for now?

Tried this in `.eslintrc.yml`:

```
env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:vue/recommended
rules:
  vue/no-parsing-error: 0
```
