### ISSUE TITLE
--fix leaves trailing spaces

### ISSUE THREAD

**Issue by rchl** [vuejs/eslint-plugin-vue#583]
**Tell us about your environment**

* **ESLint Version:** 5.6.0
* **eslint-plugin-vue Version:** 4.0.0
* **Node Version:** 8.11.3

**Please show your full configuration:**

.eslintrc.yaml
```yaml
---
env:
    node: true
parserOptions:
    parser: 'babel-eslint'
    ecmaVersion: 2018
    sourceType: module
plugins:
    - vue
extends:
    - 'eslint:recommended'
    - 'plugin:vue/recommended'
rules:
    indent:
        - error
        - 4
    linebreak-style: error
    no-var: error
    prefer-const: error
    quotes:
        - error
        - single
    semi: error
    no-console:
        - error
        - allow: [warn, error, info]
    vue/html-indent:
        - error
        - 4
```

**What did you do? Please include the actual source code causing the issue.**

Triggered formatting of code using `eslint --fix`

```vue
<template>
    <div a b>Foo</div>
</template>
```

**What did you expect to happen?**

Template to be formatted without leaving trailing spaces.

**What actually happened? Please include the actual, raw output from ESLint.**

Formatted code includes spaces (denoted by `<space>`) in places where line-break was added.
```vue
<template>
    <div<space>
        a<space>
        b>Foo</div>
</template>
```
